"""日本で観察されうる野鳥の種リスト（和名, 英名, 学名）。

ゼロショット分類 (photofinder/bird.py) の候補集合。ユーザが自由に追加・削除できる。
英名・学名はテキストプロンプトの精度を上げるために併記する。
"""

BIRDS: list[tuple[str, str, str]] = [
    # カワセミ科
    ("カワセミ", "Common Kingfisher", "Alcedo atthis"),
    ("ヤマセミ", "Crested Kingfisher", "Megaceryle lugubris"),
    ("アカショウビン", "Ruddy Kingfisher", "Halcyon coromanda"),
    # スズメ・カラス・身近な小鳥
    ("スズメ", "Eurasian Tree Sparrow", "Passer montanus"),
    ("メジロ", "Warbling White-eye", "Zosterops japonicus"),
    ("シジュウカラ", "Japanese Tit", "Parus minor"),
    ("ヤマガラ", "Varied Tit", "Sittiparus varius"),
    ("エナガ", "Long-tailed Tit", "Aegithalos caudatus"),
    ("ヒヨドリ", "Brown-eared Bulbul", "Hypsipetes amaurotis"),
    ("ムクドリ", "White-cheeked Starling", "Spodiopsar cineraceus"),
    ("ハシブトガラス", "Large-billed Crow", "Corvus macrorhynchos"),
    ("ハシボソガラス", "Carrion Crow", "Corvus corone"),
    ("カササギ", "Oriental Magpie", "Pica serica"),
    ("ウグイス", "Japanese Bush Warbler", "Horornis diphone"),
    ("モズ", "Bull-headed Shrike", "Lanius bucephalus"),
    ("ジョウビタキ", "Daurian Redstart", "Phoenicurus auroreus"),
    ("ルリビタキ", "Red-flanked Bluetail", "Tarsiger cyanurus"),
    ("コマドリ", "Japanese Robin", "Larvivora akahige"),
    ("オオルリ", "Blue-and-white Flycatcher", "Cyanoptila cyanomelana"),
    ("キビタキ", "Narcissus Flycatcher", "Ficedula narcissina"),
    ("ツグミ", "Dusky Thrush", "Turdus eunomus"),
    ("シロハラ", "Pale Thrush", "Turdus pallidus"),
    ("イソヒヨドリ", "Blue Rock Thrush", "Monticola solitarius"),
    ("ハクセキレイ", "White Wagtail", "Motacilla alba"),
    ("キセキレイ", "Grey Wagtail", "Motacilla cinerea"),
    ("セグロセキレイ", "Japanese Wagtail", "Motacilla grandis"),
    ("カワラヒワ", "Grey-capped Greenfinch", "Chloris sinica"),
    ("ホオジロ", "Meadow Bunting", "Emberiza cioides"),
    ("アオジ", "Black-faced Bunting", "Emberiza spodocephala"),
    ("シメ", "Hawfinch", "Coccothraustes coccothraustes"),
    ("イカル", "Japanese Grosbeak", "Eophona personata"),
    ("ベニマシコ", "Long-tailed Rosefinch", "Carpodacus sibiricus"),
    ("レンジャク", "Japanese Waxwing", "Bombycilla japonica"),
    ("ツバメ", "Barn Swallow", "Hirundo rustica"),
    ("イワツバメ", "Asian House Martin", "Delichon dasypus"),
    ("キジバト", "Oriental Turtle Dove", "Streptopelia orientalis"),
    ("ドバト", "Rock Dove", "Columba livia"),
    # キツツキ
    ("コゲラ", "Japanese Pygmy Woodpecker", "Yungipicus kizuki"),
    ("アカゲラ", "Great Spotted Woodpecker", "Dendrocopos major"),
    ("アオゲラ", "Japanese Green Woodpecker", "Picus awokera"),
    # サギ・水辺
    ("アオサギ", "Grey Heron", "Ardea cinerea"),
    ("ダイサギ", "Great Egret", "Ardea alba"),
    ("コサギ", "Little Egret", "Egretta garzetta"),
    ("チュウサギ", "Intermediate Egret", "Ardea intermedia"),
    ("ゴイサギ", "Black-crowned Night Heron", "Nycticorax nycticorax"),
    ("アマサギ", "Cattle Egret", "Bubulcus ibis"),
    ("カワウ", "Great Cormorant", "Phalacrocorax carbo"),
    ("ウミウ", "Japanese Cormorant", "Phalacrocorax capillatus"),
    ("バン", "Common Moorhen", "Gallinula chloropus"),
    ("オオバン", "Eurasian Coot", "Fulica atra"),
    ("カイツブリ", "Little Grebe", "Tachybaptus ruficollis"),
    ("カンムリカイツブリ", "Great Crested Grebe", "Podiceps cristatus"),
    ("セイタカシギ", "Black-winged Stilt", "Himantopus himantopus"),
    ("イソシギ", "Common Sandpiper", "Actitis hypoleucos"),
    ("シロチドリ", "Kentish Plover", "Charadrius alexandrinus"),
    ("タゲリ", "Northern Lapwing", "Vanellus vanellus"),
    ("タンチョウ", "Red-crowned Crane", "Grus japonensis"),
    ("トキ", "Crested Ibis", "Nipponia nippon"),
    ("コウノトリ", "Oriental Stork", "Ciconia boyciana"),
    # カモ類
    ("マガモ", "Mallard", "Anas platyrhynchos"),
    ("カルガモ", "Eastern Spot-billed Duck", "Anas zonorhyncha"),
    ("コガモ", "Eurasian Teal", "Anas crecca"),
    ("オナガガモ", "Northern Pintail", "Anas acuta"),
    ("ヒドリガモ", "Eurasian Wigeon", "Mareca penelope"),
    ("ホシハジロ", "Common Pochard", "Aythya ferina"),
    ("キンクロハジロ", "Tufted Duck", "Aythya fuligula"),
    ("オシドリ", "Mandarin Duck", "Aix galericulata"),
    ("カワアイサ", "Common Merganser", "Mergus merganser"),
    ("オオハクチョウ", "Whooper Swan", "Cygnus cygnus"),
    ("コハクチョウ", "Tundra Swan", "Cygnus columbianus"),
    ("マガン", "Greater White-fronted Goose", "Anser albifrons"),
    # 猛禽
    ("トビ", "Black Kite", "Milvus migrans"),
    ("ミサゴ", "Osprey", "Pandion haliaetus"),
    ("オオタカ", "Northern Goshawk", "Accipiter gentilis"),
    ("ノスリ", "Eastern Buzzard", "Buteo japonicus"),
    ("チョウゲンボウ", "Common Kestrel", "Falco tinnunculus"),
    ("ハヤブサ", "Peregrine Falcon", "Falco peregrinus"),
    ("オジロワシ", "White-tailed Eagle", "Haliaeetus albicilla"),
    ("オオワシ", "Steller's Sea Eagle", "Haliaeetus pelagicus"),
    ("フクロウ", "Ural Owl", "Strix uralensis"),
    ("アオバズク", "Brown Hawk-Owl", "Ninox japonica"),
    # その他
    ("キジ", "Green Pheasant", "Phasianus versicolor"),
    ("ヤマドリ", "Copper Pheasant", "Syrmaticus soemmerringii"),
    ("カッコウ", "Common Cuckoo", "Cuculus canorus"),
    ("ホトトギス", "Lesser Cuckoo", "Cuculus poliocephalus"),
    ("ヨタカ", "Grey Nightjar", "Caprimulgus jotaka"),
    ("ヤマセミ", "Crested Kingfisher", "Megaceryle lugubris"),
    ("オオヨシキリ", "Oriental Reed Warbler", "Acrocephalus orientalis"),
    ("セッカ", "Zitting Cisticola", "Cisticola juncidis"),
    ("ヒバリ", "Eurasian Skylark", "Alauda arvensis"),
    ("ウミネコ", "Black-tailed Gull", "Larus crassirostris"),
    ("ユリカモメ", "Black-headed Gull", "Chroicocephalus ridibundus"),
    ("アジサシ", "Common Tern", "Sterna hirundo"),
    ("カワガラス", "Brown Dipper", "Cinclus pallasii"),
    ("ミソサザイ", "Eurasian Wren", "Troglodytes troglodytes"),
    ("オナガ", "Azure-winged Magpie", "Cyanopica cyanus"),
    ("キクイタダキ", "Goldcrest", "Regulus regulus"),
    ("ゴジュウカラ", "Eurasian Nuthatch", "Sitta europaea"),
    ("コジュケイ", "Chinese Bamboo Partridge", "Bambusicola thoracicus"),
    ("ライチョウ", "Rock Ptarmigan", "Lagopus muta"),

    # 花鳥園・動物園などで見られる外来種・展示種 (実写テストで日本の在来種に
    # 誤マッピングされた種の対策。掛川花鳥園ほかの展示種を中心に補強)
    ("ハシビロコウ", "Shoebill", "Balaeniceps rex"),
    ("クラハシコウ", "Saddle-billed Stork", "Ephippiorhynchus senegalensis"),
    ("ベニイロフラミンゴ", "American Flamingo", "Phoenicopterus ruber"),
    ("オオフラミンゴ", "Greater Flamingo", "Phoenicopterus roseus"),
    ("コンゴウインコ", "Scarlet Macaw", "Ara macao"),
    ("ルリコンゴウインコ", "Blue-and-yellow Macaw", "Ara ararauna"),
    ("ボウシインコ", "Amazon Parrot", "Amazona"),
    ("オカメインコ", "Cockatiel", "Nymphicus hollandicus"),
    ("キバタン", "Sulphur-crested Cockatoo", "Cacatua galerita"),
    ("モモイロインコ", "Galah", "Eolophus roseicapilla"),
    ("セキセイインコ", "Budgerigar", "Melopsittacus undulatus"),
    ("オオハシ", "Toco Toucan", "Ramphastos toco"),
    ("エボシドリ", "Turaco", "Tauraco"),
    ("ホオジロカンムリヅル", "Grey Crowned Crane", "Balearica regulorum"),
    ("ハクトウワシ", "Bald Eagle", "Haliaeetus leucocephalus"),
    ("ワシミミズク", "Eurasian Eagle-Owl", "Bubo bubo"),
    ("シロフクロウ", "Snowy Owl", "Bubo scandiacus"),
    ("メンフクロウ", "Barn Owl", "Tyto alba"),
    ("クジャク", "Indian Peafowl", "Pavo cristatus"),
    ("ショウジョウトキ", "Scarlet Ibis", "Eudocimus ruber"),
    ("ヘラサギ", "Eurasian Spoonbill", "Platalea leucorodia"),
    ("カンムリヅル", "Black Crowned Crane", "Balearica pavonina"),
    ("ペンギン", "Penguin", "Spheniscidae"),
    ("ハシビロガモ", "Northern Shoveler", "Spatula clypeata"),
]

# 重複除去（種リスト編集時の事故防止）
_seen: set[str] = set()
BIRDS = [b for b in BIRDS if not (b[0] in _seen or _seen.add(b[0]))]
